### PR TITLE
[do not merge]Fix rocm gpu targets

### PR DESCRIPTION
**Pull request by reza-amd**
@deven-amd could you please take a look at this change before I submit the upstream PR.

### CODE REVIEW

**Comment by deven-amd** [comment]
keep the target sync here in sync with the one in TF here - https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/Dockerfile.rocm#L81

please drop `gfx803`, `gfx90a` and `gfx1010` from the support list

**Comment by deven-amd** [comment]
@reza-amd , how are CI jobs getting triggered and who is running them?

**Comment by reza-amd** [comment]
I think these are the upstream CI jobs. In the actions tab, it shows the upstream workflow. I am not sure if this a bug or a feature.

**Comment by reza-amd** [comment]
https://github.com/ROCmSoftwarePlatform/jax/blob/main-rocm/.github/workflows/ci-build.yaml

**Pull request closed without merging**
